### ISSUE TITLE
Core Infrastructure of the plugin [Milestone 1]

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#3]
- [x] https://github.com/10up/plugin-check/issues/4
- [x] https://github.com/10up/plugin-check/issues/5
- [x] https://github.com/10up/plugin-check/issues/6
- [x] https://github.com/10up/plugin-check/issues/7
- [x] https://github.com/10up/plugin-check/issues/10
- [x] https://github.com/10up/plugin-check/issues/11
- [x] https://github.com/10up/plugin-check/issues/12
- [x] https://github.com/10up/plugin-check/issues/13
- [x] https://github.com/10up/plugin-check/issues/16

WP CLI Class

- [x] https://github.com/10up/plugin-check/issues/30

Check Orchestration and Execution Approach with initial checks to implement first with core infrastructure

- [x] https://github.com/10up/plugin-check/issues/17
- [x] https://github.com/10up/plugin-check/issues/18

**Comment by eclarke1** [comment]
@jjgrainger do you agree with closing out these [Type] Overview issues as I don't think they add much value, considering this repo is just all for plugin check, it's easier to see progress using other labels.

**Comment by jjgrainger** [comment]
@eclarke1 yes, I will close this now
